### ISSUE TITLE
[AppProvider] Consolidate se23 logic and styles

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react#10189]
```[tasklist]
### Tasks
- [x] Clean up `AppProvider` tsx conditional logic
- [x] Clean up `AppProvider` scss
- [x] Remove any instances of the `features: {polarisSummerEditions2023}` being passed into the `AppProvider` within `polaris-react`
- [x] Remove feature prop from `PolarisTestProvider.tsx`
- [x] Remove feature prop from `react-testing.tsx`
- [x] Remove feature prop from `Frame.stories.tsx`
- [x] Remove feature prop from `.storybook/preview.js`
- [x] Remove classlist toggle for se23 but add the se23 classname hardcoded on the document root element
```

**Comment by laurkim** [comment]
Blocked until token rearchitecting work ships.

**Comment by sophschneider** [comment]
make sure that we keep the se23 classname since its being used by our consumers still https://grokt.shopify.io/results?q=Polaris-Summer-Editions-2023

instead of having the `classList.toggle` we can just add the classname to the `document.documentElement`
