### ISSUE TITLE
Pattern docs epic

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react#10314]
Log:
- This issue was repurposed Oct 5th.
- This issue was closed on Nov 7th and consolidated with a [new issue](https://github.com/Shopify/polaris-internal/issues/1173) focused on reassessing and planning.

**Goal**
The goal is to ship two new pattern sections and to update the old pattern pages into the new format.

**Priority**
The new pattern sections are not critical to our v12 docs commitment. However, it has very high value to consumers and should be published no later than two weeks after.

**Plan**
1. Complete Card layout pages "Structure" and "Spacing"
2. Add Pattern page to Card layout section
3. Complete Common actions section 
4. Migrate old pattern pages without content updates

```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/polaris/issues/10898
- [ ] https://github.com/Shopify/polaris/issues/10900
- [ ] https://github.com/Shopify/polaris/issues/10906
- [ ] https://github.com/Shopify/polaris/issues/11020
```

<details><summary>Archived issue</summary>

## Old issue from before repurposing Oct 5th

See [this issue](https://github.com/Shopify/polaris/issues/10062) for background to this shortlist.

``` 
[ tasklist ]
### Prioritized patterns (P1 & P2)
- Issue
- Issue
- Issue
```

### Runner-ups
_Patterns that we should return to or include if there's time_

| Category | Pattern | Priority | Comment |
|--------------|---------------|--------------|--------------|
| Resource CRUD: Create    | Primary action on index page                   |          P3     | Important but not new to Uplift |
|                                             | Duplicate action on details page               |         P3     | Important but not crucially inconsistent |
|                                             | Import action on index page                      |         P3     | Important but somewhat consistent |
| Resource CRUD: Read      | Access from Index page                             |         P5     | Strong pattern, no inconsistency. |
|                                             | Access from card resource lists               |         P5     |  Built into resource list. |
|                                             | Resource link                                               |     **P2**  | Important, new to Uplift |
| Resource CRUD: Update  | Edit and save on details page                    |          P3    | Strong pattern with a few big exceptions|
| Resource CRUD: Delete    | Delete bulk action on index page             |          P5     | Nothing new to bulk actions |
|                                             | Delete action on details page                    |          P3     | Is very inconsistent, not new to Uplift |
|                                             | Archive action on details page                  |          P4     | Somewhat consistent |
| Other resource actions     | Print                                                             |          P4    | Somewhat consistent |
|                                             | Preview                                                        |          P3     | No guidelines re: `view` and `preview`|
| Common card actions       | Show more                                                  |          P3     | Quite inconsistent, mixed up with "View more"|
|                                             | View all                                                        |           P3    | Inconsistent |
|                                             | View object, such as "Report"                  |           P3    | Very inconsistent. "View report" is contentious |
|                                             | Add to list/context                                      |           P3    | Audit and opinion needed. |
|                                             | Learn more                                                  |           P3    | Inconsistent, not crucial |
| Actions on items                | Copy to clipboard                                       |           P3    | Very common, no guidelines |

### Scope considerations
_Patterns that we might need but require more work_
1. **Main card patterns**: Many card patterns apply to main cards as well, but in addition to that we also have some patterns that are unique to main cards, such as common tables and lists, when to use header vs footer actions, etc. Audit needed to select the most critical ones.
2. ...

</details> 
```[tasklist]
### Tasks
```
