### ISSUE TITLE
[Card Layout] Single section, multiple inputs

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react#10317]
## Visual
![image](https://github.com/Shopify/polaris/assets/38329124/cc1c5198-d323-4c91-b1b0-76d46edf4200)

[Source]()

## Builder needs
In order to design and implement this pattern consistently, builders need to:
1. 

## Key information
1.

```[tasklist]
### Tasks
- [ ] Draft visual for critique
- [ ] Outline what builders need to understand
- [ ] Draft key information
```

**Comment by johanstromqvist** [comment]
![image](https://github.com/Shopify/polaris/assets/38329124/bc4434c7-a079-49fa-acd5-ffa26a172c1f)

We have discussed using 12px gap between card title and form layout, but in the guidelines above I've applied 8px.

Here's my rationale. Happy to discuss it further.
- 8px gap creates clear grouping in a card with a single form layout
- 8px gap is consistent with the spacing rules in cards with a single list
- Sticking to 8px gap will make one fewer rules for builders to learn
- Slightly denser
