### ISSUE TITLE
Run `border` migration in web deps with polaris peer dep

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react#10521]
>[!WARNING]
> Do not merge the PR for `online-store-ui` until the PRs for #10519 is merged and  #10521 is ready . (Checked using [the following code search](https://github.com/search?type=code&q=repo%3Ashopify%2Fpolaris+OR+repo%3Ashopify%2Fweb+OR+repo%3Ashopify%2Fapp-bridge+OR+repo%3Ashopify%2Fapp-kit+OR+repo%3Ashopify%2Fflow-app+OR+repo%3Ashopify%2Fmagic-ui+OR+repo%3Ashopify%2Fonline-store-ui+OR+repo%3Ashopify%2Fonline-store-web+OR+repo%3Ashopify%2Femail+%2F--p-border-%5B%5Cw-%5D%2B%3F%3A%2F))

Follow the steps outlined in #10520 but update the path you run the migration on for each of the following repositories/packages. 

```[tasklist]
### Web Deps with Polaris Peer Dep (WDWPPD) Migrations
- [x] Run `border` migration in [`app-bridge-host`](https://github.com/Shopify/app-bridge/tree/main/packages/app-bridge-host) (none found)
- [x] Run `border` migration in [`app-kit-internal-react`](https://github.com/Shopify/app-kit/tree/main/packages/app-kit-internal-react) [#593](https://github.com/Shopify/app-kit/pull/593)
- [x] Run `border` migration in [`flow-app`](https://github.com/Shopify/flow-app) (none found)
- [x] Run `border` migration in [`magic-ui`](https://github.com/Shopify/magic-ui) [#191](https://github.com/Shopify/magic-ui/pull/191)
- [x] Run `border` migration in [`online-store-ui`](https://github.com/Shopify/online-store-ui) [#4313](https://github.com/Shopify/online-store-ui/pull/4313)
- [x] Run `border` migration in [`online-store-web`](https://github.com/Shopify/online-store-web) [#18169](https://github.com/Shopify/online-store-web/pull/18169)
- [x] Run `border` migration in [`email`](https://github.com/Shopify/email) [#19372](https://github.com/Shopify/email/pull/19372)
```

_*List above based off [Peer dependent package release process section](https://docs.google.com/document/d/1oMcUZNOuczAH22_1bvTddx0zUgNnjeZwR7e351BJc_0/edit#heading=h.am1cr9a6xgzj) of Polaris Major Version Upgrades in the Admin doc_
