### ISSUE TITLE
[Epic] Polaris `v12.0.0` release checklist

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react#10820]
```mermaid
flowchart LR
  U[Upgrade]

  U --> abh1[App Bridge Host]
  U --> ak1[AppKit]
  U -->  fa1[Flow App]
  U --> osui1[Online Store UI]
  U --> mui1[Magic UI]

  abh1 --> R
  fa1 --> R
  osui1 --> R
  mui1 --> R
  ak1 --> R

  R[Release]

  R --> abh2[App Bridge Host]
  R --> ak2[AppKit]
  R --> fa2[Flow App]
  R --> mui2[Magic UI]
  R --> osui2[Online Store UI]

  abh2 -->   uw[Upgrade Web]
  ak2 --> uw
  fa2 --> uf2[Upgrade Flow]
  fa2 --> uw
  mui2 --> uw
  mui2 -->  uosw2[Upgrade Online Store Web]
  mui2 --> uem2[Upgrade Email]
  osui2 --> uw
  osui2 --> uosw2
  osui2--> uem2
  uf2 --> si
  uosw2 --> si
  uem2 --> si
  uw --> si
  si[Shipit]
```

## Upgrades

>[!IMPORTANT]
> Tasklists below with a `*` can be done in parallel. 

```[tasklist]
### Upgrade all `web` deps with a peer dep on `polaris`*
- [ ] https://github.com/Shopify/polaris/issues/10826
- [ ] https://github.com/Shopify/polaris/issues/10827
- [ ] https://github.com/Shopify/polaris/issues/10828
- [ ] https://github.com/Shopify/polaris/issues/10829
- [ ] https://github.com/Shopify/polaris/issues/10831
- [ ] https://github.com/Shopify/polaris/issues/10824
- [ ] https://github.com/Shopify/polaris/issues/10832
- [ ] https://github.com/Shopify/polaris/issues/10833
- [ ] https://github.com/Shopify/polaris/issues/10834
- [ ] https://github.com/Shopify/polaris/issues/10835
- [ ] https://github.com/Shopify/polaris/issues/10836
- [ ] https://github.com/Shopify/polaris/issues/10837
- [ ] https://github.com/Shopify/polaris/issues/10838
- [ ] https://github.com/Shopify/polaris/issues/10839
- [ ] https://github.com/Shopify/polaris/issues/10825
```

```[tasklist]
### Upgrade `web`* 
- [ ] https://github.com/Shopify/polaris/issues/10840
- [ ] https://github.com/Shopify/polaris/issues/10841
- [ ] https://github.com/Shopify/polaris/issues/10842
- [ ] https://github.com/Shopify/polaris/issues/10843
```

```[tasklist]
### Upgrade any apps that consume a `web` dep with a peer dep on `polaris`\*
- [ ] https://github.com/Shopify/polaris/issues/10844
- [ ] https://github.com/Shopify/polaris/issues/10920
- [ ] https://github.com/Shopify/polaris/issues/10921
- [ ] https://github.com/Shopify/polaris/issues/10845
- [ ] https://github.com/Shopify/polaris/issues/10846
- [ ] https://github.com/Shopify/polaris/issues/10922
- [ ] https://github.com/Shopify/polaris/issues/10847
- [ ] https://github.com/Shopify/polaris/issues/10848
- [ ] https://github.com/Shopify/polaris/issues/10923
- [ ] https://github.com/Shopify/polaris/issues/10919
- [ ] https://github.com/Shopify/polaris/issues/10849
```

## Releases

```[tasklist]
### Release all `web` deps with a peer dep on `polaris`
- [ ] https://github.com/Shopify/polaris/issues/10850
- [ ] https://github.com/Shopify/polaris/issues/10851
- [ ] https://github.com/Shopify/polaris/issues/10852
- [ ] https://github.com/Shopify/polaris/issues/10853
- [ ] https://github.com/Shopify/polaris/issues/10854
```

```[tasklist]
### Release `web`
- [ ] https://github.com/Shopify/polaris/issues/10855
- [ ] https://github.com/Shopify/polaris/issues/10856
- [x] [`web`] Ship updated Inter weights https://github.com/Shopify/web/pull/105977
- [ ] https://github.com/Shopify/polaris/issues/10857
```

```[tasklist]
### Upgrade apps that consume a `web` dep with a peer dep on `polaris`
- [ ] https://github.com/Shopify/polaris/issues/10858
- [ ] https://github.com/Shopify/polaris/issues/10859
- [ ] https://github.com/Shopify/polaris/issues/10860
```
