### ISSUE TITLE
[Color system] Color factory in polaris-react for theme generation

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#2034]
Build a factory for generating all necessary color variants from a given set of values applied to color roles in the `ThemeProvider` component. These variants should be generated from a small set of arguments, but should cover all use of color in our component library. 

## Background
The `ThemeProvider` component wraps all components used in a `polaris-react` application. It ingests colors as a `Theme` object, which contains a `colors` property. The `colors` property contains a number of color role properties which accept base color values. They are:

- `surface` (background colors)
- `onSurface` (colors that appear on a background)
- `interactive`
- `branded`
- `critical`
- `warning`
- `highlight`
- `success`

This limited, manageable API will then generate nearly 100 semantically-named color variants  which will be applied to our components as CSS Custom Properties.

These roles can be reassigned non-Polaris product values to customize the color scheme of a `polaris-react`-based application.

For more information, see [the project brief](https://docs.google.com/document/d/1yBvk03gp9es4ebYRhfmzvHSXeZGDWTLirC4P_uG_tuY/edit#heading=h.gxswzcyiqhvq) and [the technical design](https://docs.google.com/document/d/1yBvk03gp9es4ebYRhfmzvHSXeZGDWTLirC4P_uG_tuY/edit#heading=h.gxswzcyiqhvq)

**Comment by danrosenthal** [comment]
## Todo

- [] Nested theme providers should not override previously applied values when only a default is given
- [] `Colors` factory should warn when `surface` and `onSurface` do not meet WCAG AA color contrast requirements
- [] `branded` role should programmatically handle light and dark brands, while using accessible text on branded backgrounds.
- [] Arrive at an implementation of dark mode variants that closely matches explorations done by Creative Direction team
- [] Replace `topBar` code so that color role is still backwards compatible
- [] Test the output of the color factory, including literal output, accessible contrast, nesting behavior, and warnings

**Comment by danrosenthal** [comment]
Closing this in favor of more targeted issues:
- https://github.com/Shopify/polaris-ux/issues/395
- https://github.com/Shopify/polaris-ux/issues/394
- https://github.com/Shopify/polaris-ux/issues/392
