### ISSUE TITLE
Navigation component polish and fixes

### ISSUE THREAD

**Issue by jessebc** [Shopify/polaris-react#3434]
Rollup of navigation component polish and fixes

- [ ] Disabled navigation items look enabled https://github.com/Shopify/polaris-react/issues/3432
- [x] Update height of parent navigation items https://github.com/Shopify/polaris-react/issues/3431
- [ ] Update navigation to consume new tokens https://github.com/Shopify/polaris-react/issues/3385
- [x] lower priority: Orders badge is sitting low in the nav item https://github.com/Shopify/polaris-react/issues/3451
