### ISSUE TITLE
Typography foundations

### ISSUE THREAD

**Issue by yesenia-perezcruz** [Shopify/polaris-react#4523]
[Project brief](https://docs.google.com/document/d/1H47OrDqWAlmMyIuVk_NjjkTjC2Gcm3yTMVrl49vYgx4/edit?usp=sharing)  |  [Vault project](https://vault.shopify.io/projects/25298)

## Problem summary

The admin UI today is lacking a strong sense of hierarchy due to a narrow type scale range, unclear and inconsistent use of spacing around text, and a lack of flexibility in our typography components. This leads teams to diverge from mainline and create new components or hard coded css values for typography. 

Since the release of v9, we have ~75% coverage of typography in `shopify/polaris` components and only ~8% coverage of typography in custom components in `shopify/web.`

Creating and simplifying  tokens, adding flexibility to components, and providing guidance for typography will allow us to increase coverage, make changes to our type at scale, and increase the quality of the admin for our merchants.

### Intended outcomes

- We'll improve Polaris coverage for typography
- Our users will have a consistent way to apply type in the admin along with a way to override the sensible defaults when needed.
- Our users will have guidance and freedom on how to use and apply typography in the admin without deviating from Polaris.
- Our users can easily build a wide range of pages and features with a strong sense of hierarchy without the need to create custom solutions to typography.

**In scope**

- Update / create typography components
- Update / create typography tokens: size, weight, fontfamily, etc.
- Replace all values in old typography tokens with hard coded values. This will allow us to update the typography tokens and components without changing the existing UI.
- Update / create typography guidance + examples
- Release new version of `polaris` with updated typography foundations
- Release guidance and examples

**Out of scope**

- Updating individual components with new text styles - this will be a follow up project
- Updating individual pages in the admin with new text styles / components

### Key assumptions

- Existing typography tokens and components are limiting
- Lack of range in styling of typography is causing teams to find custom solutions
- Lack of consistent use of vertical spacing between type elements causes unclear hierarchy
- Lack of clear hierarchy makes it hard for merchants to quickly scan and find information on a page
- It's easier for teams to write their own custom css for typography because Polaris typography components are hard to use and not flexible

### Guiding principles

- We trust our users to make the best decisions for the problem they're trying to solve.
- We want to enable designers and developers to speak the same language.
- Typography should help establish a clear hierarchy and help merchants understand what to do next.

## Tasks

- [x] https://github.com/Shopify/polaris/issues/5917
- [x] https://github.com/Shopify/polaris/issues/5914
- [x] https://github.com/Shopify/polaris/issues/5916
- [x] https://github.com/Shopify/polaris/issues/5915
- [x] https://github.com/Shopify/polaris-team-tasks/issues/21
- [x] https://github.com/Shopify/polaris/issues/5699
- [x] #4627
- [x] Create project brief
- [x] Create vault project
- [x] Audit polaris type components and tokens
