### ISSUE TITLE
Create new multiselect autocomplete component

### ISSUE THREAD

**Issue by laurkim** [Shopify/polaris-react#4964]
### Problem

The current flow in admin to interact with tags is in a less than ideal state. Some of the main functions of the existing `TagCard` component are:

- tags displayed if there are applied tags
- you can add/remove tags in the autocomplete component (from Polaris)
- clicking "View all tags" opens a modal to edit tags
- you can sort by popularity/alphabetically in the tags modal

The proposed solution is to build a new multiselect autocomplete component to replace the necessity of the flow to click the "View all tags" to open the modal and be allowed to edit tags.

### Tasks

- [x] #5055
- [x] #4965
- [x] Write project brief to help define project deadlines and scope the project
- [x] #5015
- [x] #5017
- [x] https://github.com/Shopify/web/issues/57730
- [x] ~https://github.com/Shopify/web/issues/57729~
- [x] ~https://github.com/Shopify/web/issues/58219~
- [x] ~https://github.com/Shopify/web/issues/58244~
- [x] #5146 
- [x] #5149
- [x] #5150
- [x] #5151
- [x] #5148
- [x] #5188
- [x] #5310 
- [x] https://github.com/Shopify/polaris-icons/pull/1441
- [x] https://github.com/Shopify/polaris-icons/pull/1442
- [x] https://github.com/Shopify/polaris/pull/5321
- [x] https://github.com/Shopify/web/issues/58023
- [x] Partner with PSN for new multiselect rollout ([care doc](https://docs.google.com/document/d/1vV5QTz7X5VGCR5HOwukXNYgLnupuGBwJCyN5PTRL7HM/edit#))
- [x] #5384 
- [x] https://github.com/Shopify/polaris-styleguide/pull/5602
- [x] #5303 
- [x] #5392 
- [x] #5151 
- [x] #5563 
- [x] #5564 
- [x] https://github.com/Shopify/web/pull/62106
- [x] https://github.com/Shopify/web/pull/62732
- [x] https://github.com/Shopify/web/pull/62459
- [x] #5567 
- [x] #5571 
- [x] #5580 
- [x] #5624 
- [x] #5584 
- [x] #5485 
- [x] #5587 
- [x] #5616 
- [x] #5618 
- [x] https://github.com/Shopify/web/issues/58220
- [x] https://github.com/Shopify/web/issues/58221
- [x] https://github.com/Shopify/web/issues/58241
- [x] https://github.com/Shopify/web/issues/60248
- [x] https://github.com/Shopify/web/pull/63241
- [ ] https://github.com/Shopify/help/issues/29585
- [x] https://github.com/Shopify/web/pull/65078
- [x] #5931
- [ ] https://github.com/Shopify/web/issues/63585
- [ ] #5957
- [ ] https://github.com/Shopify/web/issues/63572
- [ ] https://github.com/Shopify/web/pull/65251
- [ ] https://github.com/Shopify/web/issues/65243
- [ ] https://github.com/Shopify/web/pull/65244

### Relevant links
- [Project brief](https://docs.google.com/document/d/16jmas-3FREThmdCKDHui44K80IMiAvqVBia6mYkxqME/edit?usp=sharing)
- [Vault project](https://vault.shopify.io/projects/23639)

**Comment by sarahill** [comment]
I've got some questions that I'm just gonna drop here to keep track. Don't need to answer them right now just things I am wondering about that may or may not need to be considered for this project.

General questions
- Will this be a new component or will it be updating the current `Autocomplete` or `Combobox`?
  - I assumed it would be a new component but as I was looking at what we have I was just curious

Polaris component questions
- Why do we have `Autocomplete` and `Combobox`?
- They do the same basic thing... I vaguely remember something about accessibility issues with the current autocomplete and Combobox being more semantically correct.

Deliver tag work questions
- Did they use an autocomplete in Polaris-next in web?
    - Doesn’t look like they’re using the Polaris-react version

**Comment by laurkim** [comment]
@sarahill for the deliver tag work question, I was looking specifically at the [TagsAutocomplete](https://github.com/Shopify/web/blob/486aa271b40dfeb7f0cedccc522b969bb64e5ea6/app/components/TagCard/components/TagsAutocomplete/TagsAutocomplete.tsx#L2) that is being used in the Deliver team's TagCard. But I think there is also an existing [TagsAutocomplete](https://github.com/Shopify/web/blob/486aa271b40dfeb7f0cedccc522b969bb64e5ea6/app/components/TagsAutocomplete/TagsAutocomplete.tsx#L5) that uses the `polaris-next` one which is confusing. Maybe the existing TagsAutocomplete hasn't been deprecated yet?

**Comment by laurkim** [comment]
Oh I think [this issue](https://github.com/Shopify/polaris-react/issues/789) might have context on why autocomplete and checkbox both exist. The autocomplete GitHub label had already existed prior to me making this issue so I'm just looking through some of the history.

**Comment by laurkim** [comment]
Closing as complete because we've [shipped](https://github.com/Shopify/web/pull/63375) new tag multiselect pattern in Admin and haven't gotten any bug reports in the 60+ mins its been live
