### ISSUE TITLE
Tooling roadmap

### ISSUE THREAD

**Issue by martenbjork** [Shopify/polaris-react#5351]
## API

Long term vision: The API is the source of truth for Polaris; tokens, documentation, coverage statistics and more. Developers are often building new tools and experiences using data from our API. Small changes in our data instantly trickles down into other tools which amplifies the impact of the changes.

#### Sprint 1: Tooling MVP
- [x] Set up a Next.js API
- [x] Expose our tokens through a simple REST endpoint
- [x] #5399

#### Sprint 2: Tooling improvements
- [x] #5400

## Dashboard
Long term vision: We’re the most data driven design systems team on the planet. We have a continuous stream of data that tells us how our design system is performing. The dashboard collects all the data in one place.

#### Sprint 1: Tooling MVP
- [x] Ship PR that improves data collection scripts and UX

#### Sprint 2: Tooling improvements
- [x] #5395

## Website
Long term vision: We have an awesome website that we are proud of. It’s easy to work with and we’re constantly shipping improvements. The website still contains documentation, but many crafters now prefer to get the docs through the VSCode and Figma plugins. Therefore, the website is just one of many outlets for us.

#### Sprint 1: Tooling MVP
- [x] Add a new page that lists all of the tokens
- [x] Add a page that explains the value of using tokens

#### Sprint 2: Tooling improvements
- [x] #5396

## Figma UI Kit
Long term vision: The Figma UI kit accelerates designers across Shopify. It supports work in all fidelities — from wireframes to pixel perfect. Designers rely on it but also know when to deviate from it and come up with custom solutions.

#### Sprint 1: Tooling MVP
- [x] Update the UI Kit to use the Figma styles that are based on tokens
- [x] Push the update to the organization

#### Sprint 2: Tooling improvements
- [x] #5397

## Polaris for Figma
Long term vision: Our Figma plugin is an essential tool for Shopify UX. The plugin brings designers context-aware documentation, starter templates, design file QA, developer hand-off help and more — right inside Figma. It saves designers a ton of time, helps UX:ers craft coherent experiences and makes collaboration with devs a breeze.

### Sprint 1: Tooling MVP
- [x] Set up new plugin according to Figma’s docs
- [ ] Add linter that finds non-token colors in your design file
- [ ] Distribute plugin to a small set of beta users

### Sprint 2: Tooling improvements
- [x] #5398

## Polaris for VSCode
Long term vision: Our VSCode plugin is an essential tool for FEDs working with Polaris. It autocompletes, catches errors and teaches best practices. Because it offers all things Polaris right inside VSCode, developers don’t have to stop their work to visit our docs. The result is maintained flow and saved time. As a result, FEDs love Polaris for VSCode.

#### Sprint 1: Tooling MVP
- [x] Scaffold bare bones plugin
- [x] Add support for autocompleting tokens
- [x] #5367
- [x] #5387
- [x] #5388

#### Sprint 2: Tooling improvements
- [x] #5368
- [x] #5369
- [x] #5370
- [x] #5366

## Linters
Long term vision: Our opinion on "coverage" is codified through a set of linting rules. These rules are used on the coverage dashboard, in VSCode and in CI.

#### Sprint 1: Tooling MVP
- [x] #5371
- [ ] Export rules as a single package
- [ ] Use package to calculate coverage on the coverage dashboard
- [ ] Use package on CI
- [ ] Use package in VSCode (?)

**Comment by alex-page** [comment]
We have already broken a part:
- [Figma Plugin](https://github.com/Shopify/polaris/issues/5231)
- [VSCode](https://github.com/Shopify/polaris/issues/5457)

This issue should be closed once the remaining tasks are broken into vault projects.
