### ISSUE TITLE
Update Polaris colors and color tokens

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react#6920]
## Summary 
An improved color token infrastructure will dramatically improve the experience of Shopifolk building for the Admin, increase [mainline coverage of custom components](https://polaris-coverage.shopifycloud.com/) by making Polaris more extensible, allow for large scale design changes with a lot more ease and speed in the future and allow us to improve the visual design of the Admin by hand picking a more cohesive and vibrant color palette that better meets merchant needs.## Issue summary

## Outcomes
- Create new infrastructure for handling the new abstractions while only exposing what we want to ensure teams use the system properly
- Create new color palettes for both functional colors and accent/decoration colors
- Create new token naming conventions and semantic token
- Mapping tokens to Polaris components
- Get new tokens into repo

## Tasks

- [x]  Create new color scales for primary palette
- [x] Create new accent color palette
- [x] Create naming convention for semantic tokens
- [x] Map current tokens to new semantic tokens
- [x] Test new colors on Polaris components and full screens across admin 
- [x] Add palette tokens to repo
- [x] Add semantic tokens to repo

**Comment by alex-page** [comment]
3 more apps to go
- [x] `shop-server`
- [x] `email`
- [ ] `pos-channel`
