### ISSUE TITLE
Show legacy patterns in pattern index

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react#8949]
We received some good feedback that it feels strange for the legacy patterns to live outside of the Polaris website page hierarchy. They are currently accessible from a link on the patterns index page, but it takes users to a new index that can't be navigated to.

We separated the legacy patterns from the new patterns because they follow a completely different content format. The new ones provide shorter, more focused, copy and sample code. We didn't want to weaken user trust by a mix of the legacy and new pattern formats.

However, we can make the legacy patterns fit into the page hierarchy better while still preserving separation so that users understand they are different before they view a specific pattern.

Let's move the legacy patterns to be listed on the new patterns index page, but placed below the new patterns in their own sub-section.

Here is a basic mock-up for illustrative purposes:

![Image](https://user-images.githubusercontent.com/421723/231546157-8f6186ed-b4a8-455c-89e4-eb01ebef5d62.png)

**Tasks**
- [ ] Design how the legacy patterns can be added to the new pattern index page
- [ ] Add legacy patterns to patterns index page
- [ ] Add legacy patterns to left nav with `legacy` badge, below all of the new patterns

**Comment by jesstelford** [comment]
Initial pass done in https://github.com/Shopify/polaris/pull/9062

> Add legacy patterns to left nav with legacy badge, below all of the new patterns

I wasn't able to do this due to the way our nav is automatically generated from the .md files; the pattern page has its own rendering engine which isn't compatible with the legacy patterns, but in order to show legacy patterns in the left nav, we would have to render the legacy patterns as new patterns. Catch-22 (unless we go and update all the legacy patterns to render like new patterns which might take a bit of effort).

**Comment by johanstromqvist** [comment]
Thanks @jesstelford!

> in order to show legacy patterns in the left nav, we would have to render the legacy patterns as new patterns

It's not ideal, but I think it's ok to not make a custom workaround for the legacy patterns since they are intended to be there only for a limited period of time. As long as they can be found in the index, that's good enough imo. Agree?

**Comment by johanstromqvist** [comment]
I think Sean's "basic mock-up for illustrative purposes" works well. Is there anything that might need specification or extra design considerations?

The outstanding task is to update the banner. Here are my suggestions:
- [ ] Update the banner style to the standard doc site one (see ref below).
- [ ] Use headline `New` and background `--surface-information` to correspond to the badge in the nav
- [ ] Update the banner copy to `The pattern documentation is evolving. [Join the discussion] to make it better.`
