### ISSUE TITLE
Top bar improvements minor polish

### ISSUE THREAD

**Issue by gladys-ng** [Shopify/polaris-react#9028]
### Problems

There's a few polish improvements to the top bar in the Figma UI kit that I missed the first time around 😅. [Link to branch](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/branch/YdQddJZNHZTD9ytjaVvbxy/Polaris-Components?node-id=434%3A2197&t=bS1E6GqaQys79bBA-1)

```[tasklist]
### Tasks
- [ ] Prototype hover states for buttons in the top bar
- [ ] Update color of the border on the unread counter to match the background color
- [ ] Add padding (8px) between alerts button and user menu button on small screens
- [ ] Fixes hover state for user menu button on small screens
- [ ] Fixes to auto layout in small screen components
```

**Comment by heyjoethomas** [comment]
Just pushed this out. Thanks for jumping in and fixing stuff.
