### ISSUE TITLE
Update contribution navigation

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react#9037]
Update "contribution" nav section to be more legible and usable. 

```[tasklist]
### Tasks
- [x] Simplify labels
- [x] Reorder pages to more logical order
- [x] Remove illustrations since it is empty
- [x] Combine some pages?
```

**Comment by heyjoethomas** [comment]
@jjgali What do you think of really simplifying the IA to something like the following? Would obviously need to find a home or decide to cut some current content. However, I think a couple of the current pages don't make a ton of sense in this section or could be combined into a much clearer page. 

- Contributing
 - Bugs
- Component changes
- New components
- Icons
- Figma UI Kit
- Documentation
- Code of conduct
