### ISSUE TITLE
Focus outline clean up and only show on focus:visible

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react#9093]
The `focus` outline is showing up incorrectly across product pages. We should address this and ensure that incorrect usage is seen as a failure in `polaris-coverage`.

- [ ] Fix Admin issues in screenshots below
  - [ ] Fix changing focus outlines on RTE
  - [ ] Fix "Select products" focus outline showing on open
  - [ ] Fix "Sales channel" popup activator focus ring showing on open
- [ ] Move https://github.com/Shopify/web/pull/83179 into `polaris-stylelint` to encourage teams to fix failures
- [ ] Reduce the focus ring mixin to render only two lines of css
- [ ] Share wins in "Quality wins" slack channel

![image](https://user-images.githubusercontent.com/19199063/234425588-cb1fd3ce-6c0d-44ee-83af-6c40a1f2b248.png)

 ![image](https://user-images.githubusercontent.com/19199063/234425623-ff57355e-9fae-45d1-b2b6-49083eb9d063.png)

https://user-images.githubusercontent.com/19199063/234430901-b958dfe1-876e-4afb-adf6-a62d45ed656d.mov

**Comment by sophschneider** [comment]
The first screenshot of the ProductResourcePicker is focusing on open because its an overridden Polaris [ListBox](https://polaris.shopify.com/components/lists/listbox), which usually has its first item focused with a blue background but is being overriden to be a focus ring instead. So its not a `focus-visible` issue and I think the best fix would be to refactor it to be an [ActionList](https://polaris.shopify.com/components/lists/action-list).

cc: @ouellettejordan @alex-page

**Comment by alex-page** [comment]
@sophschneider feel free to get draft PR's up and make assumptions. It is going to be much easier to tophat a change then talk through it here. I trust you if you want to refactor that UI.

**Comment by sam-b-rose** [comment]
@sophschneider is this currently still in progress? Do you thing we should decide to either close it out and revisit later or move to the backlog?

**Comment by sophschneider** [comment]
@samrose3 hmm yeah I think we should revisit it late/ move to the backlog. I think it would be cool if we did something similar to to aarons shadow bevel component for this

**Comment by sam-b-rose** [comment]
Sounds good, thanks Sophie!

**Comment by sophschneider** [comment]
I have a related prototype here for creating a focus ring mixin from a while ago https://github.com/Shopify/polaris/pull/9467. The PR description has my prototype thoughts!

For the same reasoning in the PR description, I think the `ShadowBevel` pattern is the way to go

**Comment by sam-b-rose** [comment]
This is great context!

>  I think the `ShadowBevel` pattern is the way to go

This wouldn't be a breaking change, correct? Just a feature add. Seems like we could address this after v12?

**Comment by alex-page** [comment]
😭
